# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogleboks', '0003_auto_20160322_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
